// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqHKc9H-3_m5sbKDX0jgDvjb_sobf6KMQ',
    appId: '1:685895588413:web:62e04b677bd82dbf5fe854',
    messagingSenderId: '685895588413',
    projectId: 'bgk-ladies-attendance',
    authDomain: 'bgk-ladies-attendance.firebaseapp.com',
    storageBucket: 'bgk-ladies-attendance.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlcG2v5fGA8OOQIMPiUWpbkDkaUf1OcIY',
    appId: '1:685895588413:android:75d025b3d87966c35fe854',
    messagingSenderId: '685895588413',
    projectId: 'bgk-ladies-attendance',
    storageBucket: 'bgk-ladies-attendance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApu0ApymwlH9mkJNlICc_UJd_ggjIpHtk',
    appId: '1:685895588413:ios:b691425afac6578c5fe854',
    messagingSenderId: '685895588413',
    projectId: 'bgk-ladies-attendance',
    storageBucket: 'bgk-ladies-attendance.firebasestorage.app',
    androidClientId: '685895588413-1q8lq05kqtiptoqa809fg4ao1sftm0aq.apps.googleusercontent.com',
    iosClientId: '685895588413-ama4eml9tuk8o9g2b2j1u5skumm17fou.apps.googleusercontent.com',
    iosBundleId: 'com.bmala.bgkladies.bgkLadies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApu0ApymwlH9mkJNlICc_UJd_ggjIpHtk',
    appId: '1:685895588413:ios:b691425afac6578c5fe854',
    messagingSenderId: '685895588413',
    projectId: 'bgk-ladies-attendance',
    storageBucket: 'bgk-ladies-attendance.firebasestorage.app',
    androidClientId: '685895588413-1q8lq05kqtiptoqa809fg4ao1sftm0aq.apps.googleusercontent.com',
    iosClientId: '685895588413-ama4eml9tuk8o9g2b2j1u5skumm17fou.apps.googleusercontent.com',
    iosBundleId: 'com.bmala.bgkladies.bgkLadies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqHKc9H-3_m5sbKDX0jgDvjb_sobf6KMQ',
    appId: '1:685895588413:web:22ff24d341bb21e65fe854',
    messagingSenderId: '685895588413',
    projectId: 'bgk-ladies-attendance',
    authDomain: 'bgk-ladies-attendance.firebaseapp.com',
    storageBucket: 'bgk-ladies-attendance.firebasestorage.app',
  );
}
